using System.Globalization;
using System.IO;
using System.Windows.Media.Media3D;

namespace MyOrganizer.Wpf.Controls;

/// <summary>
/// Unused. FDI 36 maps are generated by the shared FDI 16 classifier plus
/// <see cref="Fdi16SurfaceCurator.ApplyGeometry"/>. Kept only so old experiments
/// are not mixed back into the runtime pipeline.
/// </summary>
internal static class Fdi36SurfaceClassifier
{
    private const int IslandSize = 22;

    public static ClinicalSurfaceMap Classify(MeshGeometry3D crown)
    {
        var idx = crown.TriangleIndices;
        var nTri = idx.Count / 3;
        var labels = new ClinicalSurface[nTri];
        var occlusalDir = new Vector3D(0, 0, 1);
        if (nTri == 0)
        {
            return new ClinicalSurfaceMap
            {
                SourceCrown = crown,
                TriangleSurface = labels,
                OcclusalDirection = occlusalDir
            };
        }

        var centroids = new Point3D[nTri];
        var normals = new Vector3D[nTri];
        var minZ = double.PositiveInfinity;
        var maxZ = double.NegativeInfinity;
        var sx = 0d;
        var sy = 0d;
        var sz = 0d;
        for (var t = 0; t < nTri; t++)
        {
            var a = crown.Positions[idx[t * 3]];
            var b = crown.Positions[idx[t * 3 + 1]];
            var c = crown.Positions[idx[t * 3 + 2]];
            var centroid = new Point3D((a.X + b.X + c.X) / 3.0, (a.Y + b.Y + c.Y) / 3.0, (a.Z + b.Z + c.Z) / 3.0);
            centroids[t] = centroid;
            var nrm = Vector3D.CrossProduct(b - a, c - a);
            if (nrm.LengthSquared < 1e-18)
                nrm = occlusalDir;
            else
                nrm.Normalize();
            normals[t] = nrm;
            minZ = Math.Min(minZ, centroid.Z);
            maxZ = Math.Max(maxZ, centroid.Z);
            sx += centroid.X;
            sy += centroid.Y;
            sz += centroid.Z;
        }

        var center = new Point3D(sx / nTri, sy / nTri, sz / nTri);
        var zSpan = Math.Max(1e-9, maxZ - minZ);
        var z01 = new double[nTri];
        var facing = new double[nTri];
        for (var t = 0; t < nTri; t++)
        {
            z01[t] = (centroids[t].Z - minZ) / zSpan;
            facing[t] = Vector3D.DotProduct(normals[t], occlusalDir);
        }

        var axialCenter = AxialCenter(centroids, z01);
        var neighbors = CrownSurfaceClassifier.BuildNeighbors(idx, nTri);
        var envelope = BuildTableEnvelope(centroids, z01, facing, out var tableOrigin);
        var radius = new double[nTri];
        var envR = new double[nTri];
        for (var t = 0; t < nTri; t++)
        {
            var dx = centroids[t].X - tableOrigin.X;
            var dy = centroids[t].Y - tableOrigin.Y;
            radius[t] = Math.Sqrt(dx * dx + dy * dy);
            envR[t] = EnvAt(envelope, dx, dy);
        }

        var occlusal = new bool[nTri];
        var seedCount = 0;
        for (var t = 0; t < nTri; t++)
        {
            if (!IsTableSeed(z01[t], facing[t], radius[t], envR[t]))
                continue;
            occlusal[t] = true;
            seedCount++;
        }
        GrowTable(occlusal, neighbors, z01, facing, radius, envR);
        var grown = 0;
        for (var t = 0; t < nTri; t++)
        {
            if (occlusal[t])
            {
                labels[t] = ClinicalSurface.Occlusal;
                grown++;
            }
            else
                labels[t] = CrownSurfaceClassifier.AxialSurface(centroids[t], normals[t], axialCenter);
        }

        var islandsBefore = CountIslands(labels, neighbors);
        Cleanup(labels, neighbors, z01, facing);
        var islandsAfter = CountIslands(labels, neighbors);

        var counts = new int[5];
        foreach (var lab in labels)
            counts[(int)lab]++;

        // #region agent log
        AgentLog("J", "fdi36-classified",
            "{\"nTri\":" + nTri +
            ",\"seed\":" + seedCount + ",\"grown\":" + grown +
            ",\"occlusal\":" + counts[0] + ",\"buccal\":" + counts[1] +
            ",\"lingual\":" + counts[2] + ",\"mesial\":" + counts[3] + ",\"distal\":" + counts[4] +
            ",\"islandsBefore\":" + islandsBefore + ",\"islandsAfter\":" + islandsAfter +
            ",\"mean\":{" + MeanJson(labels, centroids) + "}}");
        // #endregion

        return new ClinicalSurfaceMap
        {
            SourceCrown = crown,
            TriangleSurface = labels,
            OcclusalDirection = occlusalDir,
            Counts = counts
        };
    }

    private static Point3D AxialCenter(Point3D[] centroids, double[] z01)
    {
        var sx = 0d;
        var sy = 0d;
        var n = 0;
        for (var t = 0; t < centroids.Length; t++)
        {
            if (z01[t] < 0.16 || z01[t] > 0.58) continue;
            sx += centroids[t].X;
            sy += centroids[t].Y;
            n++;
        }
        if (n == 0)
        {
            foreach (var p in centroids)
            {
                sx += p.X;
                sy += p.Y;
            }
            n = centroids.Length;
        }
        return new Point3D(sx / n, sy / n, 0);
    }

    private static double[] BuildTableEnvelope(Point3D[] centroids, double[] z01, double[] facing, out Point3D origin)
    {
        const int bins = 72;
        var sx = 0d;
        var sy = 0d;
        var n = 0;
        for (var t = 0; t < centroids.Length; t++)
        {
            if (z01[t] < 0.64 || facing[t] < 0.36) continue;
            sx += centroids[t].X;
            sy += centroids[t].Y;
            n++;
        }
        origin = n == 0 ? new Point3D(0, 0, 0) : new Point3D(sx / n, sy / n, 0);
        var maxR = new double[bins];
        var has = new bool[bins];
        for (var t = 0; t < centroids.Length; t++)
        {
            if (z01[t] < 0.64 || facing[t] < 0.36) continue;
            var dx = centroids[t].X - origin.X;
            var dy = centroids[t].Y - origin.Y;
            var r = Math.Sqrt(dx * dx + dy * dy);
            var bin = AngleBin(dx, dy, bins);
            if (r >= maxR[bin])
            {
                maxR[bin] = r;
                has[bin] = true;
            }
        }
        for (var i = 0; i < bins; i++)
        {
            if (has[i])
            {
                maxR[i] *= 1.05;
                continue;
            }
            var prev = i;
            var back = 0;
            do { prev = (prev - 1 + bins) % bins; back++; } while (!has[prev] && back < bins);
            var next = i;
            var fwd = 0;
            do { next = (next + 1) % bins; fwd++; } while (!has[next] && fwd < bins);
            if (!has[prev] && !has[next]) continue;
            if (!has[prev]) maxR[i] = maxR[next];
            else if (!has[next]) maxR[i] = maxR[prev];
            else maxR[i] = (maxR[prev] * fwd + maxR[next] * back) / Math.Max(1, back + fwd);
            maxR[i] *= 1.05;
        }
        return maxR;
    }

    private static int AngleBin(double dx, double dy, int bins)
    {
        var ang = Math.Atan2(dy, dx);
        var bin = (int)Math.Floor((ang + Math.PI) / (2 * Math.PI) * bins);
        return Math.Clamp(bin, 0, bins - 1);
    }

    private static double EnvAt(double[] envelope, double dx, double dy)
    {
        var bins = envelope.Length;
        var u = (Math.Atan2(dy, dx) + Math.PI) / (2 * Math.PI) * bins;
        var i0 = ((int)Math.Floor(u) % bins + bins) % bins;
        var i1 = (i0 + 1) % bins;
        var frac = u - Math.Floor(u);
        return envelope[i0] * (1 - frac) + envelope[i1] * frac;
    }

    private static bool IsTableSeed(double z, double face, double r, double env)
    {
        var inside = r <= env * 1.02;
        var near = r <= env * 1.08;
        if (inside && z > 0.60) return true;
        if (inside && z > 0.54 && face > 0.20) return true;
        if (near && z > 0.66 && face > 0.36) return true;
        if (z > 0.76 && face > 0.48) return true;
        return false;
    }

    private static void GrowTable(bool[] occlusal, List<int>[] neighbors, double[] z01, double[] facing, double[] radius, double[] envR)
    {
        var q = new Queue<int>();
        for (var t = 0; t < occlusal.Length; t++)
        {
            if (occlusal[t])
                q.Enqueue(t);
        }
        while (q.Count > 0)
        {
            var t = q.Dequeue();
            foreach (var nb in neighbors[t])
            {
                if (occlusal[nb]) continue;
                if (!CanGrow(nb, occlusal, neighbors, z01, facing, radius, envR))
                    continue;
                occlusal[nb] = true;
                q.Enqueue(nb);
            }
        }
    }

    private static bool CanGrow(int t, bool[] occlusal, List<int>[] neighbors, double[] z01, double[] facing, double[] radius, double[] envR)
    {
        var z = z01[t];
        var face = facing[t];
        var r = radius[t];
        var env = Math.Max(1e-9, envR[t]);
        if (z < 0.50) return false;
        var occN = 0;
        foreach (var nb in neighbors[t])
        {
            if (occlusal[nb]) occN++;
        }
        var inside = r <= env;
        if (inside && z > 0.56 && face > 0.14) return true;
        if (inside && occN >= 2 && z > 0.52 && face > 0.00) return true;
        if (occN >= 2 && z > 0.58 && r <= env * 1.05 && face > 0.20) return true;
        if (face > 0.38 && z > 0.62 && r <= env * 1.08) return true;
        return false;
    }

    private static void Cleanup(ClinicalSurface[] labels, List<int>[] neighbors, double[] z01, double[] facing)
    {
        ReassignIsolated(labels, neighbors, z01, facing);
        ReassignSmall(labels, neighbors);
        KeepLargest(labels, neighbors);
        Majority(labels, neighbors, z01, facing, 3);
        ReassignIsolated(labels, neighbors, z01, facing);
        ReassignSmall(labels, neighbors);
        KeepLargest(labels, neighbors);
    }

    private static void ReassignIsolated(ClinicalSurface[] labels, List<int>[] neighbors, double[] z01, double[] facing)
    {
        var next = (ClinicalSurface[])labels.Clone();
        for (var t = 0; t < labels.Length; t++)
        {
            if (neighbors[t].Count == 0) continue;
            var same = 0;
            var votes = new int[5];
            foreach (var nb in neighbors[t])
            {
                votes[(int)labels[nb]]++;
                if (labels[nb] == labels[t]) same++;
            }
            if (same >= 2) continue;
            if (labels[t] == ClinicalSurface.Occlusal && z01[t] > 0.58 && facing[t] > 0.42)
                continue;
            next[t] = Best(votes, labels[t]);
        }
        Array.Copy(next, labels, labels.Length);
    }

    private static void ReassignSmall(ClinicalSurface[] labels, List<int>[] neighbors)
    {
        var totals = new int[5];
        foreach (var lab in labels)
            totals[(int)lab]++;
        for (var s = 0; s < 5; s++)
        {
            var surface = (ClinicalSurface)s;
            foreach (var comp in Components(labels, neighbors, surface))
            {
                if (comp.Count >= IslandSize && comp.Count >= 0.01 * totals[s])
                    continue;
                var votes = new int[5];
                foreach (var t in comp)
                {
                    foreach (var nb in neighbors[t])
                    {
                        if (labels[nb] != surface)
                            votes[(int)labels[nb]]++;
                    }
                }
                var target = Best(votes, surface);
                if (target == surface) continue;
                foreach (var t in comp)
                    labels[t] = target;
            }
        }
    }

    private static void KeepLargest(ClinicalSurface[] labels, List<int>[] neighbors)
    {
        for (var s = 1; s < 5; s++)
        {
            var surface = (ClinicalSurface)s;
            var comps = Components(labels, neighbors, surface);
            if (comps.Count <= 1) continue;
            var largest = comps.OrderByDescending(c => c.Count).First();
            foreach (var comp in comps)
            {
                if (comp == largest) continue;
                var votes = new int[5];
                foreach (var t in comp)
                {
                    foreach (var nb in neighbors[t])
                    {
                        if (labels[nb] != surface)
                            votes[(int)labels[nb]]++;
                    }
                }
                var target = Best(votes, surface);
                if (target == surface) continue;
                foreach (var t in comp)
                    labels[t] = target;
            }
        }
    }

    private static void Majority(ClinicalSurface[] labels, List<int>[] neighbors, double[] z01, double[] facing, int passes)
    {
        for (var pass = 0; pass < passes; pass++)
        {
            var next = (ClinicalSurface[])labels.Clone();
            for (var t = 0; t < labels.Length; t++)
            {
                var nCount = neighbors[t].Count;
                if (nCount < 3) continue;
                var votes = new int[5];
                var same = 0;
                foreach (var nb in neighbors[t])
                {
                    votes[(int)labels[nb]]++;
                    if (labels[nb] == labels[t]) same++;
                }
                if (same >= nCount - 1) continue;
                if (labels[t] == ClinicalSurface.Occlusal && z01[t] > 0.60 && facing[t] > 0.45)
                    continue;
                next[t] = Best(votes, labels[t]);
            }
            Array.Copy(next, labels, labels.Length);
        }
    }

    private static ClinicalSurface Best(int[] votes, ClinicalSurface fallback)
    {
        var best = fallback;
        var n = votes[(int)fallback];
        for (var s = 0; s < 5; s++)
        {
            if (votes[s] <= n) continue;
            n = votes[s];
            best = (ClinicalSurface)s;
        }
        return best;
    }

    private static List<List<int>> Components(ClinicalSurface[] labels, List<int>[] neighbors, ClinicalSurface surface)
    {
        var seen = new bool[labels.Length];
        var result = new List<List<int>>();
        for (var i = 0; i < labels.Length; i++)
        {
            if (seen[i] || labels[i] != surface) continue;
            var stack = new Stack<int>();
            var comp = new List<int>();
            stack.Push(i);
            seen[i] = true;
            while (stack.Count > 0)
            {
                var t = stack.Pop();
                comp.Add(t);
                foreach (var nb in neighbors[t])
                {
                    if (seen[nb] || labels[nb] != surface) continue;
                    seen[nb] = true;
                    stack.Push(nb);
                }
            }
            result.Add(comp);
        }
        return result;
    }

    private static int CountIslands(ClinicalSurface[] labels, List<int>[] neighbors)
    {
        var n = 0;
        for (var s = 0; s < 5; s++)
        {
            foreach (var comp in Components(labels, neighbors, (ClinicalSurface)s))
            {
                if (comp.Count < IslandSize)
                    n++;
            }
        }
        return n;
    }

    private static string MeanJson(ClinicalSurface[] labels, Point3D[] centroids)
    {
        var sx = new double[5];
        var sy = new double[5];
        var sz = new double[5];
        var n = new int[5];
        for (var t = 0; t < labels.Length; t++)
        {
            var s = (int)labels[t];
            sx[s] += centroids[t].X;
            sy[s] += centroids[t].Y;
            sz[s] += centroids[t].Z;
            n[s]++;
        }
        string One(int s) => n[s] == 0 ? "0,0,0" :
            F(sx[s] / n[s]) + "," + F(sy[s] / n[s]) + "," + F(sz[s] / n[s]);
        return "\"O\":\"" + One(0) + "\",\"B\":\"" + One(1) + "\",\"L\":\"" + One(2) +
               "\",\"M\":\"" + One(3) + "\",\"D\":\"" + One(4) + "\"";
    }

    private static string F(double v) => v.ToString("0.####", CultureInfo.InvariantCulture);

    private static void AgentLog(string hypothesisId, string message, string dataJson)
    {
        var line = "{\"sessionId\":\"ee2893\",\"runId\":\"fdi36-map-v1\",\"hypothesisId\":\"" + hypothesisId +
                   "\",\"location\":\"Fdi36SurfaceClassifier.cs\",\"message\":\"" + message +
                   "\",\"data\":" + dataJson + ",\"timestamp\":" + DateTimeOffset.UtcNow.ToUnixTimeMilliseconds() + "}\n";
        try { File.AppendAllText(@"c:\Users\david\source\repos\MyOrganIzer\debug-ee2893.log", line); }
        catch { }
    }
}
